---
- name: "Apache-mysql-wordpress installation"
  become: true
  hosts: all
  vars_files:
    - lamp.vars
  tasks:
    
    - name: "Inatalling http"
      yum:
        name: httpd
        state: present
      tags:
        - lamp
            
    - name: "Installing php"
      shell: amazon-linux-extras install php7.4 -y
      tags:
        - lamp
        
    - name: "Creating virtualHost"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/httpd/conf.d/{{httpd_hostname}}.conf"
      tags:
        - lamp
        
    - name: "Creating documentRoot"
      file:
        path: "/var/www/html/{{ httpd_hostname }}"
        state: directory
		user: "{{ httpd_user }}"
		group: "{{ httpd_group }}"
      tags:
        - lamp
          
    - name: "Restarting/enabling Service"
      service:
        name: httpd
        state: restarted
        enabled: true
      tags:
        - lamp
        
    - name: "Mariadb installation"
      yum:
        name: 
          - mariadb-server
          - MySQL-python
        state: present
      tags:
        - lamp
        - mysql
        
    - name: "Restarting and enabling mariadb service"
      service:
        name: mariadb
        state: restarted
        enabled: true
      tags:
        - lamp
        - mysql
        
    - name: "Setting Root Password"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{ mysql_root_password }}"
        host_all: true
      tags:
        - lamp
        - mysql
            
    - name: "Removing anonymous users"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        user: ""
        host_all: true 
        state: absent
      tags:
        - lamp
        - mysql
            
    - name: "Creating database"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_wordpress_database }}"
        state: present
      tags:
        - lamp
        - mysql
            
    - name: "Creating user"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root_password }}"
        user: "{{ mysql_wordpress_user }}"
        password: "{{ mysql_wordpress_password }}"
        priv: '{{ mysql_wordpress_database }}.*:ALL'
      tags:
        - lamp
        - mysql
        
    - name: "Downloading WordPress"
      get_url:
        url: "{{ wp_url }}"
        dest: "/var/wordpress.tar.gz"
        
    - name: "Unzip Wordpress"
      unarchive:
        src: "/var/wordpress.tar.gz"
        dest: "/var/"
        remote_src: true
    
    - name: "Wordpress - Copying Contents"
      copy:
        src: "/var/wordpress/"
        dest: "/var/www/html/{{ httpd_hostname }}"
        remote_src: true
        owner: "apache"
        group: "apache"
            
    - name: "Creating wp-config.php from template"
      template:
        src: wp-config.php.j2
        dest: "/var/www/html/{{ httpd_hostname }}/wp-config.php"
        owner: "apache"
        group: "apache"
            
    - name: "Removing Downloaded files"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/var/wordpress"
        - "/var/wordpress.tar.gz"